version: '3'
services:
  web:
    build: .
    ports:
      - "8880:80"
    environment:
      - DB_NAME=oauth2
      - DB_USER=oauth2
      - DB_PASSWORD=oauth2
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=secret123
  db:
    image: "postgres"
    environment:
      - POSTGRES_USER=oauth2
      - POSTGRES_PASSWORD=oauth2
      - POSTGRES_DB=oauth2
    volumes:
      - test-oauth2-server-database:/var/lib/postgresql/data

volumes:
  test-oauth2-server-database:
